package com.example.itview_spring.Constant;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Genre {
    ACTION("액션"),
    ADVENTURE("어드벤처"),
    COMEDY("코미디"),
    DRAMA("드라마"),
    THRILLER("스릴러"),
    HORROR("호러"),
    FANTASY("판타지"),
    ROMANCE("로맨스"),
    NATURAL_SCIENCE("자연과학"),
    KPOP("KPOP"),
    ANIMATION("애니메이션"),
    SPORTS("스포츠"),
    MYSTERY("미스터리"),
    DOCUMENTARY("다큐멘터리"),
    SF("SF"),
    MUSIC("음악"),
    FAMILY("가족"),
    CONCERT("공연실황"),
    MUSICAL("뮤지컬"),
    BIOPIC("전기"),
    HISTORY("역사"),
    CRIME("범죄"),
    KIDS("키즈"),
    VARIETY("예능"),
    SITCOM("시트콤"),
    TV_DRAMA("TV드라마"),
    PERIOD("시대극"),
    ROMANTIC_COMEDY("로맨틱 코미디"),
    BL("BL"),
    TEENAGER("틴에이저"),
    DISASTER("재난"),
    COMICS("만화"),
    HUMANITIES("인문학"),
    ECONOMICS("경제서"),
    INVESTMENT("투자서"),
    NOVEL("소설"),
    ESSAY("에세이"),
    SELF_HELP("자기계발"),
    WAR("전쟁"),
    PLAY("희곡"),
    POETRY("시"),
    SLICE_OF_LIFE("일상"),
    HIP_HOP("힙합"),
    POP("팝"),
    MOVIE_SOUNDTRACK("영화음악"),
    TV_SOUNDTRACK("드라마음악"),
    BALLAD("발라드"),
    DANCE("댄스"),
    ROCK("록"),
    CLASSICAL("클래식"),
    INDIE("인디"),
    ELECTRONICA("일렉트로니카"),
    JPOP("JPOP"),
    RNB("알앤비"),
    TROT("트로트");

    private final String genreName;
}
